Update stboot version.
system-transparency/system-transparency pull request #169
Opened 2022-04-04 14:47 UTC by jensdrenhaus

Using stboot commit 4b208b7 introduces optimizations in parsing
of host configuration, security configuration etc. Further the
command line of stboot changed regarding logging.

Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

2022-04-04 15:46 UTC, sylv-io requested changes
To change the current default branch, you have to modify this variable too: https://github.com/system-transparency/system-transparency/blob/7132ddc6e0edc1b7fdd3383b3f7e7e8cfbe88f39/tasks/go.yml#L7

The commented out git version in `contrib/default.config` is just a hint to the current default.

2022-04-05 07:56 UTC, sylv-io approved these changes

2022-04-05 07:59 UTC, jensdrenhaus commented
> To change the current default branch, you have to modify this variable too:
> 
> https://github.com/system-transparency/system-transparency/blob/7132ddc6e0edc1b7fdd3383b3f7e7e8cfbe88f39/tasks/go.yml#L7
> 
> The commented out git version in `contrib/default.config` is just a hint to the current default.

#170

2022-04-11 09:36 UTC, bjoto approved these changes
LGTM.

2022-04-11 10:14 UTC, merged